bigflow.deploy type hints, refactoring
allegro/bigflow pull request #267
Opened 2021-06-20 12:46 UTC by beczkowb

2021-06-25 12:50 UTC, anjensan requested changes

2021-06-25 12:52 UTC, anjensan commented on bigflow/deploy.py
> +        auth_method: str = 'local_account',
str => `typing.Literal[...]`

2021-06-29 07:14 UTC, beczkowb commented on bigflow/deploy.py
> +            logger.info(f"deleting file {_blob_uri(blob)}")
done

2021-06-29 07:14 UTC, beczkowb commented on bigflow/deploy.py
> +        auth_method: str = 'local_account',
done

2021-06-29 07:14 UTC, merged